apiVersion: apps/v1
kind: Deployment
metadata:
  name: ioromero-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioromero-playground
  template:
    metadata:
      labels:
        app: ioromero-playground
    spec:
      containers:
      - name: will-app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: ioromero-playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
  labels:
    app: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-service
            port:
              number: 80
